import type { HowtoBlock, InsertHowtoEntry } from "@workspace/db";

const text = (value: string) => [{ text: value }];
const rich = (...runs: Array<{ text: string; bold?: boolean; italic?: boolean }>) => runs;
const heading = (value: string): HowtoBlock => ({ type: "heading", runs: text(value) });
const paragraph = (value: string): HowtoBlock => ({ type: "paragraph", runs: text(value) });
const item = (number: number, title: string, value: string | ReturnType<typeof rich>): HowtoBlock => ({
  type: "step",
  number,
  title,
  runs: typeof value === "string" ? text(value) : value,
});
const tip = (value: string): HowtoBlock => ({ type: "tip", runs: text(value) });

export const HOWTO_INITIAL_SEEDS: InsertHowtoEntry[] = [
  {
    id: "getting-started",
    title: "Getting started with AIO Fusion",
    description: "A walk-through of the platform, from intake to measurement.",
    type: "Guide",
    readTime: "5 min read",
    displayOrder: 0,
    status: "published",
    body: [
      heading("What AIO Fusion does"),
      paragraph("AIO Fusion helps PR and marketing teams make their clients visible to AI answer engines - ChatGPT, Claude, and others. Instead of optimising for search ranking alone, you optimise for the signals that large language models use to decide whether to mention, recommend, or cite a brand."),
      heading("The four steps"),
      item(1, "Set up your project", rich(
        { text: "Every client or brand gets its own project. Start by clicking " },
        { text: "Create Project", bold: true },
        { text: " in the Project Hub, then complete the Project Set-Up form (Section 1-7). Fill in company details, key messages, spokespeople, target audiences, and the content cadence you plan to run. The more complete the Set-Up, the better your audit and content results will be." },
      )),
      item(2, "Run your first LLM Check", rich(
        { text: "Go to " }, { text: "LLM Check / Earned Media", bold: true },
        { text: " from the sidebar. This audit sends your brand name and sector to ChatGPT and Claude simultaneously and records whether and how they mention you, who they list as competitors, and what they say. Run it before any optimisation work so you have a clean baseline." },
      )),
      item(3, "Use the content and optimisation tools", rich(
        { text: "Once you have a baseline, use " }, { text: "Content Creator", bold: true },
        { text: " to draft new press releases, articles, and case studies optimised for AI citation, and " },
        { text: "Content Optimiser", bold: true },
        { text: " to rewrite existing material with tracked changes that show exactly what was altered and why. Use " },
        { text: "Media Research", bold: true }, { text: " to build targeted journalist lists." },
      )),
      item(4, "Measure your progress", "Re-run the LLM Check after a programme of work - typically after 4-6 weeks of consistent content activity. Compare the before and after results to show clients concrete movement in AI visibility, share of voice, and competitive positioning."),
      tip("Complete as much of Project Set-Up as possible before running any audits or generating content. Sections 1-3 are the minimum; sections 4-7 add depth that significantly improves output quality."),
    ],
  },
  {
    id: "aio-diagnostic",
    title: "Running an AIO Diagnostic",
    description: "How to interpret the diagnostic score and pick the first fixes.",
    type: "Guide",
    readTime: "4 min read",
    displayOrder: 1,
    status: "published",
    body: [
      heading("What the diagnostic measures"),
      paragraph("The AIO Diagnostic (Technical GEO) analyses a website's structure and content against the six signals that AI crawlers use to assess authority and trustworthiness: content structure, factual clarity, entity signals, link authority, schema markup, and crawl accessibility. Each signal gets a band score: Strong, Good, Needs work, or Weak."),
      heading("Running the diagnostic"),
      item(1, "Enter the website URL", rich({ text: "From the sidebar, go to " }, { text: "Technical GEO / Website Audit", bold: true }, { text: ". Enter the full URL of the site you want to assess (including https://) and click Run Diagnostic. The audit takes 30-60 seconds." })),
      item(2, "Read the overall score", "The top of the report shows a composite score out of 100 and an overall band. Use this as the headline metric for client reporting. A score below 50 means significant structural work is needed before content investment will have full impact."),
      item(3, "Work through the six signals", rich({ text: "Each signal section shows the band, a one-sentence summary, and a list of specific findings. Focus on " }, { text: "Needs work", bold: true }, { text: " and " }, { text: "Weak", bold: true }, { text: " bands first - these have the highest impact-to-effort ratio." })),
      item(4, "Share with the developer", "The export button at the top of the report produces a clean HTML file you can send directly to a web developer. It contains the full findings in plain language with no jargon."),
      heading("What the bands mean"),
      { type: "paragraph", runs: rich(
        { text: "Strong (80-100):", bold: true }, { text: " This signal is working in your favour. Maintain it.\n" },
        { text: "Good (60-79):", bold: true }, { text: " Solid, with room for incremental improvement.\n" },
        { text: "Needs work (40-59):", bold: true }, { text: " This signal is neutral or slightly negative. Address within 4-6 weeks.\n" },
        { text: "Weak (0-39):", bold: true }, { text: " This signal is actively reducing AI visibility. Prioritise immediately." },
      ) },
      tip("Re-run the diagnostic 6-8 weeks after the developer has implemented the recommended changes. A before-and-after comparison is one of the clearest deliverables you can show a client."),
    ],
  },
  {
    id: "comms-planner",
    title: "Building a comms plan that scores",
    description: "Turning the Comms Planner into AI authority impact.",
    type: "Article",
    readTime: "4 min read",
    displayOrder: 2,
    status: "published",
    body: [
      heading("What the Comms Planner does"),
      paragraph("The Comms Planner helps you build a structured content calendar that maps press releases, articles, and commentary to the key messages you defined in Project Set-Up. Rather than planning by channel alone, it plans by narrative authority - ensuring each piece of output reinforces the same consistent signals that AI models look for."),
      heading("Creating a plan"),
      item(1, "Open Comms Planner from the sidebar", rich({ text: "Select your project first, then click " }, { text: "Comms Planner", bold: true }, { text: ". You will see the current month's calendar view and a list of any existing planned items." })),
      item(2, "Add a new content item", rich({ text: "Click " }, { text: "Add item", bold: true }, { text: " and select the content type (press release, article, commentary, case study, etc.), the planned publication date, the target publication or outlet, and the key message it should reinforce from your Project Set-Up." })),
      item(3, "Link to content output", "Once a piece is drafted in Content Creator, you can link it back to the planner item. This closes the loop between plan and output and lets you track what was actually delivered against what was planned."),
      item(4, "Review cadence", "AI models weight recency and consistency. A plan with one press release per month, consistently delivered, will outperform irregular bursts over time. Use the planner to hold the cadence."),
      tip("Align your comms plan with the same narrative threads as your Project Set-Up key messages. Inconsistency across outputs is one of the main reasons brands score poorly on entity clarity in audits."),
    ],
  },
  {
    id: "content-optimiser",
    title: "Optimising content for AI citation",
    description: "Tracked-changes editing for press releases, articles, and case studies.",
    type: "Guide",
    readTime: "5 min read",
    displayOrder: 3,
    status: "published",
    body: [
      heading("What the Content Optimiser does"),
      paragraph("The Content Optimiser takes a piece of existing content - a press release, article, blog post, or case study - and rewrites it to improve its chances of being cited by AI answer engines, while preserving the author's original voice and argument. Changes are shown as tracked edits so you can see exactly what was altered and accept or reject each change before publishing."),
      heading("Running an optimisation"),
      item(1, "Paste your content", rich({ text: "From the sidebar, go to " }, { text: "Content Optimiser", bold: true }, { text: ". Paste the full text of the content piece you want to optimise. Include the headline and any subheadings." })),
      item(2, "Select content type", "Choose the content type from the dropdown (press release, article, case study, etc.). This adjusts the optimisation approach - a press release is treated differently from a long-form article."),
      item(3, "Add any specific guidance", "If there are particular claims to preserve, a specific brand voice guide, or sections to avoid changing, add these in the guidance field. The optimiser will work within those constraints."),
      item(4, "Review tracked changes", "The output shows the revised text with additions highlighted in green and removals in red. Each significant change includes a brief rationale. Review each change and use the accept/reject controls."),
      item(5, "Copy and publish", "Once you are satisfied with the accepted changes, copy the clean version and publish via your normal channel."),
      heading("What the optimiser changes"),
      paragraph("The main areas of intervention are: entity clarity (making the subject and its relationships unmistakable), factual precision (replacing vague language with specific data points), structural signalling (adding or improving subheadings so models can parse the content hierarchy), and citation anchoring (ensuring claims are attributed to named sources where relevant)."),
      tip("Optimise existing high-performing content first - a press release that already got good coverage is worth making AI-friendly because it may already exist in model training data."),
    ],
  },
  {
    id: "measuring-growth",
    title: "Measuring AI authority growth",
    description: "Reading the cycle history and released-coverage metrics.",
    type: "Article",
    readTime: "3 min read",
    displayOrder: 4,
    status: "published",
    body: [
      heading("The LLM Check as your measurement tool"),
      paragraph("The LLM Check / Earned Media Audit is the primary measurement instrument in AIO Fusion. Each run is timestamped and saved to your project's audit history. Running it at regular intervals - before a programme starts, and every 4-6 weeks thereafter - gives you a longitudinal dataset that shows genuine movement in AI visibility."),
      heading("What to look for between runs"),
      item(1, "Overall mentions", "Are both ChatGPT and Claude mentioning the brand? At the start of a programme, clients with low authority are often absent entirely. Appearing, even briefly, is a measurable first step."),
      item(2, "Share of voice", "The report shows which competitors are mentioned alongside your client and how often. A rising share of voice - your client mentioned more frequently relative to competitors - is a strong indicator of improving authority."),
      item(3, "Sentiment and framing", "Beyond presence, look at how the brand is described. Are the descriptions becoming more precise, more positive, or more aligned with your key messages? This reflects whether the content programme is shaping model understanding."),
      item(4, "Consistency across models", "If ChatGPT mentions the brand but Claude does not (or vice versa), there is still work to do. Consistent presence across both models is the target."),
      heading("Reporting to clients"),
      paragraph("Export the LLM Check report using the HTML export button. The report includes all probe results, competitor data, and the AI commentary in a clean, client-ready format. Run a baseline export before starting any work and save it - it is the most important proof point for demonstrating ROI at the end of a programme."),
      tip("Save every audit run - do not overwrite old ones. The saved audit history in your project sidebar is your evidence trail. Clients who see a clear before-and-after are significantly more likely to renew."),
    ],
  },
  {
    id: "multiple-projects",
    title: "Working with multiple projects",
    description: "Project Hub, archived projects, and switching between them.",
    type: "Article",
    readTime: "3 min read",
    displayOrder: 5,
    status: "published",
    body: [
      heading("The Project Hub"),
      paragraph("The Project Hub is the home screen of the platform. It lists all your active projects and gives you quick access to create a new one, browse your archived work, and open this guidance library. Each project is a self-contained workspace with its own Set-Up data, audits, content, and comms plan. In billing language, an \"additional project\" or \"instance\" means another independent workspace for a brand, client, or programme."),
      heading("Switching between projects"),
      item(1, "Select from the Hub", "From the Project Hub, click any project card to open it. The sidebar and all tools update instantly to show data for that project only."),
      item(2, "Use the project switcher", "Once inside a project, you can switch to another without going back to the Hub. Click the project name at the top of the sidebar to open the switcher dropdown and select a different project."),
      item(3, "Back to Hub", rich({ text: "Click the AIO Fusion logo or the " }, { text: "Back to Hub", bold: true }, { text: " option in the sidebar to return to the Project Hub at any time." })),
      heading("Archiving a project"),
      { type: "paragraph", runs: rich(
        { text: "When a client programme ends, archive the project rather than deleting it. Archived projects are moved to the " },
        { text: "Archived Projects", bold: true },
        { text: " section of the Hub. All data - Set-Up, audits, content, and comms plan - is retained and fully searchable. If the client returns, you can restore the project and pick up exactly where you left off." },
      ) },
      heading("Project limits"),
      paragraph("Client accounts include 1 active project during the beta trial, while Agency accounts include 2. Paid allowances and purchased project packs can add workspaces at any time - contact the team or use the billing section of your account settings. Archived projects do not count towards your active project limit. Project packs add workspaces; they do not add runtime capacity or parallel environments inside an existing project."),
      tip("Use clear, specific project names that include the client or brand name. When you have multiple projects it becomes much easier to navigate quickly."),
    ],
  },
];