import { db } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

export async function seedSupportFaq(): Promise<void> {
  const { supportFaqTable } = await import("@workspace/db");

  // Check if table already has enough entries — re-seeds if below target
  const existing = await db.execute(sql`SELECT COUNT(*) AS cnt FROM support_faq`);
  const cnt = Number((existing.rows[0] as { cnt: string | number })?.cnt ?? 0);
  if (cnt >= 150) {
    logger.info({ cnt }, "seedSupportFaq: FAQ entries already seeded, skipping");
    return;
  }
  // If fewer than 150, truncate and re-seed with the full set
  if (cnt > 0) {
    await db.execute(sql`TRUNCATE TABLE support_faq RESTART IDENTITY CASCADE`);
    logger.info({ cnt }, "seedSupportFaq: Truncating to re-seed with full 150+ entry set");
  }

  const entries = [
    // ── Getting Started ──────────────────────────────────────────────────────
    {
      category: "Getting Started",
      question: "What is AIO Fusion and who is it for?",
      answer: "AIO Fusion is a Generative Engine Optimisation (GEO) platform built for PR and marketing professionals. It helps brands measure, plan, and improve how often they appear in AI-generated answers — from tools like ChatGPT and Claude. It's designed for agencies managing multiple clients, and for brands managing their own visibility in-house.",
      keywords: "what is aio fusion, overview, intro, who is it for, purpose, generative engine optimisation, geo platform",
      displayOrder: 10,
    },
    {
      category: "Getting Started",
      question: "How do I log in?",
      answer: "Go to the platform login page and enter either your username or your registered email address, plus your password. If your agency uses Google sign-in, click the Google button instead. If you've forgotten your password, contact your agency admin or platform support.",
      keywords: "login, sign in, password, username, email, google, access, forgot password",
      displayOrder: 20,
    },
    {
      category: "Getting Started",
      question: "What's the difference between an Agency account and a Client account?",
      answer: "An Agency account can create and manage multiple Client workspaces under it — think of it as the parent. A Client account is a single brand workspace. Agencies see all their clients' projects; clients only see their own. If you're an in-house team with a single brand, you'll typically be set up as a Client.",
      keywords: "agency, client, account type, difference, roles, hierarchy, workspace, sub-account",
      displayOrder: 30,
    },
    {
      category: "Getting Started",
      question: "How do I create a new project?",
      answer: "From the Project Hub, click \"New Project.\" Give it a name and your brand's website URL. Once created, start with the Project Set-Up (Intake Form) to give the platform the brand context it needs to run audits and generate content accurately.",
      keywords: "new project, create project, project hub, add project, start",
      displayOrder: 40,
    },
    {
      category: "Getting Started",
      question: "Can I have more than one project?",
      answer: "Yes. Agency accounts can manage up to 2 projects by default, with higher limits available on request. Admin accounts have no limit. Each project is a separate brand workspace with its own audits, content, and settings.",
      keywords: "multiple projects, project limit, how many projects, agency projects",
      displayOrder: 50,
    },
    {
      category: "Getting Started",
      question: "What is GEO (Generative Engine Optimisation)?",
      answer: "GEO is the practice of improving how often and how accurately a brand appears in AI-generated answers — from tools like ChatGPT and Claude. Unlike traditional SEO (which targets search result rankings), GEO targets the training signals and citation patterns that AI models use to select which brands and sources to reference.",
      keywords: "geo, generative engine optimisation, what is geo, ai visibility, ai mentions, seo vs geo",
      displayOrder: 60,
    },
    {
      category: "Getting Started",
      question: "How do I navigate between different tools in AIO Fusion?",
      answer: "All tools are accessible from the left-hand sidebar. The sidebar is organised by function: Project Set-Up at the top, then audit tools (LLM Check, Technical GEO), content tools (Creator, Optimiser, Comms Planner, Media Research), and Archive / Reports at the bottom. Click any item to go directly to that tool.",
      keywords: "navigation, sidebar, how to use, find tools, where is, menu",
      displayOrder: 70,
    },
    {
      category: "Getting Started",
      question: "Does AIO Fusion work on mobile devices?",
      answer: "AIO Fusion is a web platform designed primarily for desktop use. It is accessible on tablets and mobile devices via a browser, but some features — particularly the audit results tables and the Comms Planner — are best experienced on a larger screen. We recommend using a desktop or laptop for detailed work.",
      keywords: "mobile, tablet, phone, browser, responsive, desktop, works on mobile",
      displayOrder: 80,
    },
    // ── Project Set-Up ───────────────────────────────────────────────────────
    {
      category: "Project Set-Up",
      question: "What is the Intake Form and why do I need to fill it in?",
      answer: "The Intake Form (also called Project Set-Up) is where you tell AIO Fusion everything it needs to know about a brand: its sector, products, target audience, spokespeople, competitors, and more. This context is used by every audit, content tool, and planner in the platform. The more accurately you complete it, the better every output will be.",
      keywords: "intake form, project setup, brand context, why fill in, set up, required, form",
      displayOrder: 10,
    },
    {
      category: "Project Set-Up",
      question: "How long does the Intake Form take to complete?",
      answer: "A basic set-up takes 10-15 minutes. A thorough one — with full competitor details, buyer personas, key messages and spokesperson bios — takes 30-45 minutes. We recommend completing as much as possible before running your first audit, as richer context leads to significantly better results.",
      keywords: "intake form, how long, time, complete, fill in, setup time",
      displayOrder: 20,
    },
    {
      category: "Project Set-Up",
      question: "Can I edit the Intake Form after the first save?",
      answer: "Yes, you can update the Intake Form at any time. Go to \"Project Set-Up\" in the sidebar. Changes take effect immediately for any new audits or content you run — they don't retroactively change previously completed audits.",
      keywords: "edit intake form, update setup, change brand info, re-save, update project",
      displayOrder: 30,
    },
    {
      category: "Project Set-Up",
      question: "Do I need to fill in every section of the Intake Form?",
      answer: "No — you can save at any point and return later. However, the platform's completeness score will indicate which sections are missing. Some tools (like the LLM Check audit) require at minimum the company name, sector, and website URL. We recommend working towards 80%+ completeness for best results.",
      keywords: "intake form, required fields, mandatory, completeness, skip, optional",
      displayOrder: 40,
    },
    {
      category: "Project Set-Up",
      question: "What should I put in the 'Key Messages' section?",
      answer: "Key messages are the 3-5 core things you want AI models — and your target audience — to know and remember about the brand. They should be factual, differentiated claims, not taglines. For example: 'First UK firm to achieve ISO 42001 AI governance certification' rather than 'We're the best AI firm around.'",
      keywords: "key messages, what to write, messaging, core messages, brand messages, examples",
      displayOrder: 50,
    },
    {
      category: "Project Set-Up",
      question: "How do I add competitors to my project?",
      answer: "In the Intake Form, scroll to the Competitor section. Add up to 10 competitors by entering their brand name and website URL. The LLM Check audit will then measure their AI visibility alongside yours, giving you share-of-voice comparisons. Update competitors any time to keep results relevant.",
      keywords: "competitors, add competitor, competitor list, rival, share of voice, intake form competitors",
      displayOrder: 60,
    },
    {
      category: "Project Set-Up",
      question: "What are LLM Queries and how are they generated?",
      answer: "LLM Queries (section 1.6 of the Intake Form) are the actual questions the platform sends to ChatGPT and Claude during the LLM Check audit. They are AI-generated from your brand context and categorised into Discovery, Shortlist, and Comparison queries. You can regenerate them once every 21 days from the Project Set-Up page.",
      keywords: "llm queries, what are they, how generated, 1.6, discovery shortlist comparison, regenerate, 21 day lock",
      displayOrder: 70,
    },
    {
      category: "Project Set-Up",
      question: "What is 'Section 1 – Earned Media Message Framework' in the Intake Form?",
      answer: "Section 1 is the most important section of the Intake Form. It defines your brand's core narrative for AI visibility: the boilerplate descriptor, your primary and supporting messages, the evidence that backs them up, and the topics and phrases you want associated with the brand. Everything in this section directly influences how the Content Creator and Optimiser generate and score output.",
      keywords: "section 1, message framework, earned media, boilerplate, primary message, intake form section 1",
      displayOrder: 80,
    },
    {
      category: "Project Set-Up",
      question: "What is 'Core Boilerplate' in the Intake Form?",
      answer: "Core Boilerplate is the standard 250-word descriptor used at the end of every press release and communications piece. It should summarise the company — what it does, who it serves, and why it matters — in factual, citable language. Avoid marketing superlatives; write it like a Wikipedia entry.",
      keywords: "core boilerplate, company descriptor, 250 word, what is it, how to write, boilerplate",
      displayOrder: 90,
    },
    {
      category: "Project Set-Up",
      question: "What is 'Message Hierarchy' in Section 1?",
      answer: "Message Hierarchy is the structured list of your primary message (the single most important claim) and supporting messages (additional factual claims that reinforce the primary). This hierarchy ensures that the Content Creator and Optimiser always lead with the most strategically important point and layer in evidence consistently.",
      keywords: "message hierarchy, primary message, supporting messages, section 1, intake form, hierarchy",
      displayOrder: 100,
    },
    {
      category: "Project Set-Up",
      question: "What should I put in the 'Evidence / Online Evidence' field?",
      answer: "This field is for factual, verifiable proof points that back up your key messages — published reports, awards, case study data, certifications, third-party endorsements, or notable media coverage. Strong evidence makes AI models more likely to cite your brand as a credible source. The more specific and verifiable the better.",
      keywords: "evidence, online evidence, proof points, what to put, citations, facts, case study, awards",
      displayOrder: 110,
    },
    {
      category: "Project Set-Up",
      question: "What is the 'Semantic Phrase Guide & Topics' field?",
      answer: "This is where you enter the specific words, phrases, and topic clusters you want associated with your brand in AI responses. Think of these as the terms you want to 'own' in the AI's understanding of your sector — e.g. 'AI governance', 'responsible technology', 'carbon-neutral logistics'. Include both technical terms and natural language phrases.",
      keywords: "semantic phrase guide, topics, what is it, keywords, phrases, semantic, topics to own",
      displayOrder: 120,
    },
    {
      category: "Project Set-Up",
      question: "What should I put in the 'What to Avoid' field?",
      answer: "List any terms, comparisons, or associations you want to steer clear of in generated content — competitor names you don't want mentioned, outdated product names, sensitive topics, or language that doesn't fit the brand tone. The Content Creator and Optimiser use this to filter their output accordingly.",
      keywords: "what to avoid, avoid, exclusions, blacklist, competitor names, tone, content restrictions",
      displayOrder: 130,
    },
    {
      category: "Project Set-Up",
      question: "What does the 'Optimise' button on a text field do?",
      answer: "The Optimise button (available on longer text fields like the boilerplate and evidence fields) sends the current text to the AI for a GEO-focused rewrite. It improves clarity, adds E-E-A-T markers, and ensures the language is structured for AI citation. You can accept or discard the suggestion — your original text is preserved until you save.",
      keywords: "optimise button, ai rewrite, text field, what does it do, optimise field, intake form button",
      displayOrder: 140,
    },
    {
      category: "Project Set-Up",
      question: "What is 'Section 2 – FAQ & Customer Questions'?",
      answer: "Section 2 captures the questions your actual customers and prospects ask — both before and after becoming clients. These questions train the platform on what information AI models are likely to be asked about your sector, helping the audit and content tools align with real-world search and conversational intent.",
      keywords: "section 2, faq, customer questions, intake form section 2, questions",
      displayOrder: 150,
    },
    {
      category: "Project Set-Up",
      question: "What are 'Post-Client Questions' in the Intake Form?",
      answer: "Post-Client Questions are questions your customers ask after they've become clients — onboarding queries, common support questions, 'how do I' questions. Including these helps the platform generate content that addresses the full customer journey, not just the sales funnel.",
      keywords: "post client questions, after sales, existing client, intake form, section 2",
      displayOrder: 160,
    },
    {
      category: "Project Set-Up",
      question: "What are 'Misconceptions' in the Intake Form?",
      answer: "Misconceptions are false or misleading beliefs that exist in the market about your brand, product, or sector. For example: 'People think we only serve large enterprise clients, when actually we work with mid-market businesses too.' Including these helps the Content Creator and Optimiser proactively address and correct them.",
      keywords: "misconceptions, false beliefs, myths, what is it, intake form, correct misconceptions",
      displayOrder: 170,
    },
    {
      category: "Project Set-Up",
      question: "What is 'Section 3 – Audience & Intent Mapping'?",
      answer: "Section 3 defines who the brand's target audience is in granular detail — their job roles, sectors, pain points, desired outcomes, and how they make buying decisions. This section is used to personalise content output and to ensure the LLM Check audit uses queries that reflect the real questions your audience is asking.",
      keywords: "section 3, audience, intent mapping, target audience, buyer personas, icp",
      displayOrder: 180,
    },
    {
      category: "Project Set-Up",
      question: "What is the difference between 'Ideal Target Client' and 'ICP' in the Intake Form?",
      answer: "Ideal Target Client is a narrative description of who the perfect client is — their situation, mindset, and what makes them a great fit. ICP (Ideal Client Profile) is the structured version: job title, company size, sector, geography, and budget range. Both are used together to sharpen the audit queries and content targeting.",
      keywords: "ideal target client, icp, ideal client profile, difference, audience, target client",
      displayOrder: 190,
    },
    {
      category: "Project Set-Up",
      question: "What should I put in 'Pain Points'?",
      answer: "Pain Points are the problems, frustrations, and challenges your ideal clients face before they find your solution. Be specific — 'Struggling to prove ROI to the board' is more useful than 'Marketing challenges'. These are used to align content and audit queries with the actual language your audience uses when searching for solutions.",
      keywords: "pain points, challenges, problems, what to put, audience, intake form",
      displayOrder: 200,
    },
    {
      category: "Project Set-Up",
      question: "What are 'Outcomes' in the Intake Form?",
      answer: "Outcomes are the specific results and transformations your clients experience after working with you — the measurable improvements, time savings, revenue gains, or competitive advantages. Including strong outcome statements helps the Content Creator produce case-study-style content that AI models treat as high-credibility evidence.",
      keywords: "outcomes, results, transformation, benefits, what clients get, intake form outcomes",
      displayOrder: 210,
    },
    {
      category: "Project Set-Up",
      question: "What are 'Trust Signals' in Section 4?",
      answer: "Trust Signals are external validators that confirm your brand's credibility — accreditations, certifications, industry memberships, notable clients (where public), awards, and years in business. AI models weight these signals heavily when deciding whether to cite a brand as authoritative. Include any you have, even minor ones.",
      keywords: "trust signals, credibility, certifications, awards, accreditations, section 4, business fundamentals",
      displayOrder: 220,
    },
    {
      category: "Project Set-Up",
      question: "What are 'Trading Names' and why do they matter?",
      answer: "Trading Names are any names the company operates under other than its legal name — shortened names, product brand names, or former names. This helps the LLM Check audit recognise when the brand is mentioned under any of its aliases, so citations aren't missed and your scores are accurate.",
      keywords: "trading names, aliases, former name, brand name, legal name, section 4",
      displayOrder: 230,
    },
    {
      category: "Project Set-Up",
      question: "What is the Completeness Score on the Intake Form?",
      answer: "The Completeness Score (shown as a percentage at the top of the Project Set-Up page) tracks how much of the Intake Form you've filled in across all sections. A higher score means more context for the platform's AI tools, leading to better audit accuracy and content quality. Aim for 80%+ before your first audit run.",
      keywords: "completeness score, percentage, progress, how complete, intake form score, what does it mean",
      displayOrder: 240,
    },
    {
      category: "Project Set-Up",
      question: "What does 'Export Project Data' do?",
      answer: "Export Project Data downloads a PDF summary of everything in your Intake Form — all brand context, messages, audience profiles, and queries. This is useful for sharing brand context with colleagues, briefing copywriters, or keeping an offline record of your project configuration.",
      keywords: "export project data, download, pdf, intake form export, brand context, project summary",
      displayOrder: 250,
    },
    // ── LLM Check / Earned Media Audit ────────────────────────────────────────
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does the Earned Media Visibility Audit measure?",
      answer: "The Earned Media Visibility Audit (LLM Check) queries ChatGPT and Claude with brand-relevant questions — discovery queries, shortlist queries, and comparison queries — then measures whether and how the brand is mentioned in their answers. It produces an Authority Index score, citation rate, sentiment, and share of voice vs. competitors.",
      keywords: "llm check, earned media audit, what does it measure, authority index, citation rate, share of voice, brand mentions",
      displayOrder: 10,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "How long does the Earned Media Audit take to run?",
      answer: "The audit typically takes 3-8 minutes to complete. It's running live queries across ChatGPT and Claude in parallel and processing the responses in real time. You'll see results stream in as they complete.",
      keywords: "how long, audit time, duration, wait, running, llm check time",
      displayOrder: 20,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is the Authority Index score?",
      answer: "The Authority Index is a 0-100 score that summarises how consistently a brand appears in AI-generated answers across its key topics. It combines citation rate (how often the brand is mentioned), sentiment (positive vs. neutral vs. negative framing), and prominence (whether the brand leads the answer or is buried). Higher is better.",
      keywords: "authority index, score, what is it, 0-100, how is it calculated, meaning",
      displayOrder: 30,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "Why can't I run the audit more than once every 21 days?",
      answer: "The 21-day lock prevents over-querying the LLMs and keeps your results meaningful. AI model responses don't change significantly day-to-day. Running too frequently adds cost and noise without adding insight. The lock resets exactly 21 days after your last run.",
      keywords: "21 day lock, audit limit, how often, frequency, why can't I run, locked, wait",
      displayOrder: 40,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "My brand scored 0% in the audit — what does that mean?",
      answer: "A 0% score means the brand was not mentioned in any of the AI model responses for the queries tested. This is actually a common starting point for newer or smaller brands. It tells you there is significant work to do on your earned media visibility — the platform's content and comms tools can help you build from here.",
      keywords: "zero score, 0%, not mentioned, brand not found, no citations, starting point",
      displayOrder: 50,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is 'Share of Voice' in the audit results?",
      answer: "Share of Voice measures what percentage of all brand mentions across the tested queries belong to your brand versus your competitors. If 10 brands were mentioned across all probes and yours appeared 4 times, your share of voice is 40%. It contextualises your score relative to the competitive landscape.",
      keywords: "share of voice, sov, competitors, comparison, what is share of voice, relative score",
      displayOrder: 60,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "Which AI models does the LLM Check audit query?",
      answer: "The LLM Check audit runs queries against ChatGPT (OpenAI) and Claude (Anthropic). These are the two dominant AI assistants used by consumers and businesses for information discovery and shortlisting. Perplexity and other AI search tools are not currently included in the audit scope.",
      keywords: "which models, chatgpt, claude, openai, anthropic, ai models tested, perplexity, not included",
      displayOrder: 70,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is the 'Business Type' input on the LLM Check?",
      answer: "Business Type is a short descriptor of how the brand operates — e.g. 'B2B SaaS', 'Professional services', 'Consumer retail'. It helps the platform contextualise the audit queries correctly. It's pre-filled from your Intake Form but you can override it for a specific audit run without changing the Intake Form.",
      keywords: "business type, input, llm check, what is it, b2b, saas, override",
      displayOrder: 80,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is the 'ICP Profile' input on the LLM Check configuration?",
      answer: "ICP Profile is a brief description of the ideal client the brand is targeting — used to calibrate the audit queries to the right audience context. For example: 'Mid-market HR Directors at manufacturing companies'. It's drawn from your Intake Form and can be overridden for a specific run.",
      keywords: "icp profile, ideal client profile, llm check, input, what is it, configuration",
      displayOrder: 90,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What are Discovery, Shortlist, and Comparison queries?",
      answer: "These are the three types of questions the audit sends to ChatGPT and Claude. Discovery queries are broad awareness questions ('Who are the leading providers of X?'). Shortlist queries simulate a buyer narrowing down options ('What are the best B2B platforms for Y?'). Comparison queries test specific head-to-head scenarios ('How does Brand A compare to Brand B?'). All three map to different stages of the buyer journey.",
      keywords: "discovery queries, shortlist queries, comparison queries, what are they, query types, audit questions",
      displayOrder: 100,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does the 'Scorecard' show in the audit results?",
      answer: "The Scorecard is a breakdown of your performance across multiple GEO dimensions: Presence (were you mentioned?), Prominence (how early in the response?), Sentiment (positive, neutral, or negative framing), Share of Voice, and Narrative Accuracy (did the AI describe you correctly?). Each dimension has a score and a brief explanation.",
      keywords: "scorecard, audit results, dimensions, presence, prominence, sentiment, narrative accuracy, breakdown",
      displayOrder: 110,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is 'Presence' in the audit scorecard?",
      answer: "Presence measures how often your brand was mentioned at all across the full set of audit probes — expressed as a percentage. A Presence of 60% means the brand appeared in 6 out of every 10 queries tested. This is the most fundamental GEO metric: you can't score well on any other dimension if you're not present.",
      keywords: "presence, scorecard, what is it, audit, cited, mentioned, percentage, fundamental metric",
      displayOrder: 120,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is 'Prominence' in the audit scorecard?",
      answer: "Prominence measures where in the AI's response your brand appears when it is mentioned — near the top (high prominence) or buried at the end of a long list (low prominence). A brand mentioned first in 80% of responses scores higher on prominence than one that's always fifth in a list of ten.",
      keywords: "prominence, where mentioned, position, response, scorecard, ranking in response",
      displayOrder: 130,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What are 'Narrative Signals' in the audit results?",
      answer: "Narrative Signals summarise how the AI models actually describe your brand when they mention it — what topics and associations they link to you, how accurately they reflect your key messages, and whether any incorrect information appeared. This section highlights gaps between how you want to be perceived and how AI models currently portray you.",
      keywords: "narrative signals, how described, associations, accuracy, brand narrative, key messages, audit",
      displayOrder: 140,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What is the 'Query Evidence Log'?",
      answer: "The Query Evidence Log is the full list of every probe sent to ChatGPT and Claude during the audit, with the result for each. You can expand any row to see the exact response the AI gave, whether your brand was mentioned, and the context around the mention. This is the raw evidence behind your scores.",
      keywords: "query evidence log, probe list, raw results, expand row, full response, audit detail",
      displayOrder: 150,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does 'Anchored' mean on a query tag in the Evidence Log?",
      answer: "'Anchored' means the query was modified by the platform to include a clarifying reference to your brand before sending — for example, turning a generic question into a more targeted one. This is used for Comparison queries where context is needed to get a meaningful AI response. Anchored queries are flagged so you know they weren't sent verbatim.",
      keywords: "anchored, query tag, evidence log, what does it mean, clarified query, modified query",
      displayOrder: 160,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does 'Mention Context' show when I expand a query row?",
      answer: "Mention Context shows the exact sentence or passage from the AI's response where your brand was referenced. This lets you see not just that you were mentioned, but how — what context, what framing, and alongside which other brands or claims. It's the most direct evidence of how AI models are portraying you.",
      keywords: "mention context, expand row, evidence log, response detail, exact mention, how mentioned",
      displayOrder: 170,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does 'Print Report' do on the audit?",
      answer: "Print Report generates a formatted PDF of the audit results — including your scores, the scorecard, narrative signals, and the query evidence log. It's designed to be shared with clients or stakeholders as a professional deliverable. The PDF is generated in your browser's print dialog.",
      keywords: "print report, pdf, export, audit report, share, download, client report",
      displayOrder: 180,
    },
    {
      category: "LLM Check / Earned Media Audit",
      question: "What does 'Delete Audit' do?",
      answer: "Delete Audit permanently removes a saved audit run from your project history. This cannot be undone. If you need to remove an audit — for example, one run with incorrect settings — use this option. Deleted audits are also removed from the trend charts on the Report page.",
      keywords: "delete audit, remove audit, permanent, undo, audit history, delete run",
      displayOrder: 190,
    },
    // ── Technical GEO / Website Audit ─────────────────────────────────────────
    {
      category: "Technical GEO / Website Audit",
      question: "What does the Website Visibility Audit check?",
      answer: "The Website Visibility Audit (Technical GEO / Diagnostic) checks your website against the technical and structural signals that influence AI model citations — including structured data, crawlability, page authority signals, content depth, E-E-A-T signals, and more. It produces an overall readiness score and detailed recommendations by category.",
      keywords: "website audit, technical geo, diagnostic, what does it check, website visibility, seo, structured data",
      displayOrder: 10,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "Do I need to give access to my website for the Technical GEO audit?",
      answer: "No. The audit works from the website URL you provide — it analyses the publicly accessible version of your site. You don't need to install any tracking code or provide admin access. Just ensure the URL in your Project Set-Up is correct.",
      keywords: "website access, give access, install code, tracking, how does it work, website url",
      displayOrder: 20,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What is an E-E-A-T signal and why does it matter for GEO?",
      answer: "E-E-A-T stands for Experience, Expertise, Authoritativeness, and Trustworthiness — Google's quality framework, which AI models also use as a proxy for citation-worthiness. Websites that clearly demonstrate expert authorship, cite credible sources, and maintain factual accuracy are more likely to be referenced in AI answers.",
      keywords: "eeat, e-e-a-t, experience, expertise, authority, trust, what is it, why does it matter, google, signals",
      displayOrder: 30,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "How often should I run the Technical GEO audit?",
      answer: "We recommend running the Technical GEO audit after any major website update, and at minimum once per quarter. The audit measures your site's structural GEO readiness, which changes when you update your site architecture, add or remove pages, or change your content structure. Unlike the LLM Check, there is no enforced waiting period between Technical GEO runs.",
      keywords: "how often, technical geo, audit frequency, quarterly, run again, website audit frequency",
      displayOrder: 40,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What is the 'AIO Readiness Score'?",
      answer: "The AIO Readiness Score is a 0-100 overall rating of how well your website is technically prepared for AI citation. It aggregates scores across all the categories the diagnostic checks: structured data, content architecture, authority signals, E-E-A-T, and more. Use it to track improvement over time as you implement recommendations.",
      keywords: "aio readiness score, what is it, 0-100, readiness, technical geo score, overall score",
      displayOrder: 50,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What are the 'Category Scores' in the Technical GEO results?",
      answer: "Category Scores break the overall Readiness Score down by specific technical areas — for example, Schema Markup, Site Architecture, Content Authority, Crawlability, and Link Signals. Each category gets its own score and a list of specific recommendations, so you know exactly where to focus your development effort.",
      keywords: "category scores, schema, architecture, authority, crawlability, breakdown, technical geo, specific scores",
      displayOrder: 60,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What are 'Priority Actions' and 'Critical Gaps' in the audit?",
      answer: "Priority Actions are the highest-impact improvements you can make to your website's GEO readiness — listed in order of expected score improvement. Critical Gaps are the areas where your site is actively missing signals that AI models rely on. Address Critical Gaps first, then work through Priority Actions for maximum score improvement.",
      keywords: "priority actions, critical gaps, recommendations, what to fix, audit recommendations, improve score",
      displayOrder: 70,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What does 'Copy Vibe-Code Prompt' do?",
      answer: "Copy Vibe-Code Prompt copies a pre-formatted technical prompt to your clipboard that you can paste directly into an AI coding assistant (like Claude or ChatGPT) to implement the recommended schema and technical fixes on your website. It's a shortcut for developers — the prompt contains the specific changes needed based on your audit results.",
      keywords: "vibe code prompt, copy prompt, developer, implement, schema, technical fixes, code prompt, what does it do",
      displayOrder: 80,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What does 'Copy SEO Improvements' do?",
      answer: "Copy SEO Improvements copies a plain-language summary of all the recommended SEO and GEO improvements to your clipboard, formatted as a clear action list. This is useful for briefing a developer, copywriter, or web agency without sharing the full technical audit.",
      keywords: "copy seo improvements, copy to clipboard, brief developer, recommendations, what does it do",
      displayOrder: 90,
    },
    {
      category: "Technical GEO / Website Audit",
      question: "What is the 'Homepage Content' paste field on the Website Audit?",
      answer: "If your website uses JavaScript rendering or is behind a login, the audit may not be able to crawl it automatically. In that case, you can manually paste in your homepage content (copy the visible text from your homepage) into this field so the audit can analyse the content directly. The URL-based scan always runs first; this field supplements it.",
      keywords: "homepage content, paste field, manual input, website content, javascript, behind login, crawl",
      displayOrder: 100,
    },
    // ── Content Creator ────────────────────────────────────────────────────────
    {
      category: "Content Creator",
      question: "What types of content can the Content Creator generate?",
      answer: "The Content Creator can generate press releases, news articles, thought leadership pieces, social media posts, and award submissions. All output is grounded in your brand's Intake Form data — so the content uses the correct tone, key messages, spokespeople, and sector context automatically.",
      keywords: "content creator, what can it create, press release, article, social post, types of content",
      displayOrder: 10,
    },
    {
      category: "Content Creator",
      question: "Can I edit content after the Creator generates it?",
      answer: "Yes. All generated content is fully editable in the Content Creator editor after generation. You can adjust the copy, add or remove sections, then use the Content Optimiser to check whether your edits maintain or improve the GEO signals.",
      keywords: "edit content, modify, change, after generation, editable, content creator edit",
      displayOrder: 20,
    },
    {
      category: "Content Creator",
      question: "How do I export or download generated content?",
      answer: "Use the Export button in the Content Creator to download the content as a formatted document. Content is also saved to your Content Library (Archive) automatically, so you can retrieve it later from the Archive section in the sidebar.",
      keywords: "export, download, save content, copy, how to export, content library, archive",
      displayOrder: 30,
    },
    {
      category: "Content Creator",
      question: "Why does the Content Creator say I've reached my usage limit?",
      answer: "Content generation is subject to a fair usage limit of 50 actions per project per month. This covers content creation and optimisation runs. If you hit the limit, it resets at the start of the next calendar month. For higher limits, contact info@aiofusions.ai.",
      keywords: "usage limit, fair usage, 50 actions, limit reached, quota, monthly limit, content limit",
      displayOrder: 40,
    },
    {
      category: "Content Creator",
      question: "What is a 'Standfirst' in the Content Creator?",
      answer: "A standfirst is the brief paragraph that sits directly below a headline in a press release or news article — sometimes called a deck or subheadline. It gives readers the key facts in 2-3 sentences before the full article begins. The Content Creator fills this in automatically based on the headline and key messages, and you can edit it freely.",
      keywords: "standfirst, what is it, deck, subheadline, press release, article, content creator",
      displayOrder: 50,
    },
    {
      category: "Content Creator",
      question: "What does the 'Spokesperson Picker' do?",
      answer: "The Spokesperson Picker lets you select which company spokesperson — an executive, director, or named expert — will be quoted in the generated content. Spokespeople are set up in your Intake Form. Choosing one ensures the content uses the right name, title, and attributed quote style for that person.",
      keywords: "spokesperson picker, who is quoted, executive, director, quote, intake form spokesperson, content creator",
      displayOrder: 60,
    },
    {
      category: "Content Creator",
      question: "What are 'Media Target Categories' in the Content Creator?",
      answer: "Media Target Categories let you select which type of publication or audience you're writing for — trade press, national press, lifestyle media, regional, or digital. The Content Creator adjusts the tone, jargon level, and structure of the output to suit the target publication type.",
      keywords: "media target categories, target audience, publication type, trade press, national press, content creator",
      displayOrder: 70,
    },
    {
      category: "Content Creator",
      question: "What does 'Create AI Draft' do?",
      answer: "Create AI Draft sends your selected content type, spokesperson, target category, and Intake Form context to the AI, which then generates a full first draft. You'll see the content stream in section by section. Once complete, you can edit freely, optimise with the Content Optimiser, or accept and archive it.",
      keywords: "create ai draft, generate, what does it do, stream, content creator, draft",
      displayOrder: 80,
    },
    {
      category: "Content Creator",
      question: "What does 'Accept & Archive' do?",
      answer: "Accept & Archive saves the current content piece to your Archive (Content Library) and marks it as finalised. Once archived, it appears in the Archive section in the sidebar and can be accessed from the Release Gateway when it's ready to publish or distribute.",
      keywords: "accept and archive, save, finalise, content library, archive, what does it do",
      displayOrder: 90,
    },
    {
      category: "Content Creator",
      question: "What does 'Push to Comms Planner' do?",
      answer: "Push to Comms Planner creates a new entry in the Comms Planner calendar for this content piece — so it appears on your communications schedule. You'll be asked to set a planned publication date and it will inherit the content type and title automatically.",
      keywords: "push to comms planner, add to planner, schedule, calendar, what does it do, content creator",
      displayOrder: 100,
    },
    {
      category: "Content Creator",
      question: "What is 'Action Notes' in the Content Creator?",
      answer: "Action Notes is a free-text field where you can add specific instructions or context for the AI draft — for example, 'Focus on the UK market launch', 'Include a reference to the Q3 results', or 'Keep the tone formal'. These notes supplement your Intake Form context for this specific piece.",
      keywords: "action notes, instructions, context, specific direction, content creator, notes field",
      displayOrder: 110,
    },
    {
      category: "Content Creator",
      question: "What is the 'Change Log' in the Content Creator?",
      answer: "The Change Log tracks all AI-generated edits and optimisations made to a piece of content during a session — so you can see exactly what was changed, why, and in what order. This is useful when reviewing optimised content with a client or colleague, as every change has a reasoning note attached.",
      keywords: "change log, audit trail, what changed, edits, optimiser, content creator, reasoning",
      displayOrder: 120,
    },
    // ── Content Optimiser ─────────────────────────────────────────────────────
    {
      category: "Content Optimiser",
      question: "What does the Content Optimiser do?",
      answer: "The Content Optimiser analyses a piece of text and rewrites or annotates it to improve its GEO signals — increasing the likelihood that AI models will cite or reference it. It adds structured claims, improves E-E-A-T markers, strengthens source citations, and ensures key messages are prominent. Every change is annotated with a reasoning note.",
      keywords: "content optimiser, what does it do, how does it work, improve content, geo signals, rewrite",
      displayOrder: 10,
    },
    {
      category: "Content Optimiser",
      question: "What is the 'GEO score' shown by the Content Optimiser?",
      answer: "The GEO score is a 0-100 rating of how well a piece of content is optimised for AI citation. It measures factors like the presence of structured factual claims, E-E-A-T signals, source citations, entity clarity, and semantic relevance to the brand's key topics. The optimiser shows you the score before and after each optimisation.",
      keywords: "geo score, content score, what is it, before after, optimiser score, rating",
      displayOrder: 20,
    },
    {
      category: "Content Optimiser",
      question: "How long does the Content Optimiser take to run?",
      answer: "Optimisation typically takes 30-90 seconds depending on the length of the content. You'll see the optimised version and annotations stream in as they're generated.",
      keywords: "optimiser time, how long, duration, wait, processing",
      displayOrder: 30,
    },
    {
      category: "Content Optimiser",
      question: "Can I paste in content from any source to optimise it?",
      answer: "Yes. The Content Optimiser accepts any text you paste in — press releases, web copy, blog posts, articles, or social posts. You don't need to have created the content in AIO Fusion. Simply paste the text, set the content type and target audience, then run the optimisation.",
      keywords: "paste content, any source, existing content, external content, copy paste, optimise external",
      displayOrder: 40,
    },
    {
      category: "Content Optimiser",
      question: "What do 'Accept Changes' and 'Reject Changes' do in the Optimiser?",
      answer: "After optimisation runs, each suggested change is shown alongside the original text. 'Accept Changes' applies a specific suggestion to your content — replacing the original with the improved version. 'Reject Changes' discards a suggestion and keeps your original text. You can accept and reject individual changes independently.",
      keywords: "accept changes, reject changes, what does it do, apply suggestion, keep original, optimiser",
      displayOrder: 50,
    },
    {
      category: "Content Optimiser",
      question: "What does 'Push to Planner' do from the Optimiser?",
      answer: "Push to Planner adds the current optimised content piece to the Comms Planner as a scheduled activity. This is the final step in the content workflow: create → optimise → schedule. You'll set the planned publication date and it will appear on your communications calendar.",
      keywords: "push to planner, optimiser, schedule, comms planner, workflow, content pipeline",
      displayOrder: 60,
    },
    // ── Comms Planner ─────────────────────────────────────────────────────────
    {
      category: "Comms Planner",
      question: "What is the Comms Planner?",
      answer: "The Comms Planner is a forward-looking planning tool that lets you map out PR and marketing activities over a period — press releases, events, campaigns, awards — and scores each activity for its predicted GEO impact. It helps you prioritise activities that will most improve AI visibility.",
      keywords: "comms planner, what is it, planning tool, pr planning, forward-looking, activities, schedule",
      displayOrder: 10,
    },
    {
      category: "Comms Planner",
      question: "How does the Comms Planner score activities?",
      answer: "Each planned activity is scored against the brand's current GEO positioning and key messages. The planner assesses factors like topical relevance, likely media coverage, and how well the activity reinforces the signals AI models use to build brand associations. Higher-scoring activities should be prioritised.",
      keywords: "comms planner, how does it score, scoring, activity score, priority, ranking",
      displayOrder: 20,
    },
    {
      category: "Comms Planner",
      question: "Can I export the Comms Planner as a calendar or document?",
      answer: "Yes, you can export the Comms Planner as a PDF or CSV. Use the Export button in the planner view. The export includes all planned activities, their scores, and any notes or content you've attached to them.",
      keywords: "export planner, download, calendar, pdf, csv, comms planner export",
      displayOrder: 30,
    },
    {
      category: "Comms Planner",
      question: "How many activities can I add to the Comms Planner?",
      answer: "There is no hard limit on the number of activities you can add to the Comms Planner. However, we recommend focusing on the next 3-6 months and limiting to 15-20 key activities for the scoring and prioritisation to be most useful. A very large plan with many low-priority items can obscure the signal.",
      keywords: "comms planner, how many, activities, limit, number, how much can I add",
      displayOrder: 40,
    },
    {
      category: "Comms Planner",
      question: "What is the 'Projected Total Score' on the Comms Planner?",
      answer: "The Projected Total Score is an aggregate estimate of the GEO impact your planned activities are expected to deliver over the selected period — based on the types, volume, and quality of planned communications. It's a planning metric, not a guaranteed outcome, and updates as you add or remove activities.",
      keywords: "projected total score, comms planner, what is it, estimated impact, aggregate score, planning",
      displayOrder: 50,
    },
    {
      category: "Comms Planner",
      question: "What do the progress bars (Visibility and Authority) mean on the Comms Planner?",
      answer: "The Visibility bar shows how much of your planned activity targets broad brand awareness (getting mentioned more often). The Authority bar shows how much targets brand credibility (being cited as an expert source). A healthy plan should have a balance of both. You can use these to spot if your plan is too heavily weighted in one direction.",
      keywords: "visibility bar, authority bar, progress bars, comms planner, what do they mean, balance",
      displayOrder: 60,
    },
    {
      category: "Comms Planner",
      question: "What does 'Calendar View' vs 'List View' show?",
      answer: "Calendar View displays your planned activities on a monthly calendar grid — useful for spotting gaps, clashes, and pacing. List View shows the same activities in a table format with columns for type, title, status, planned date, and GEO score — useful for sorting and bulk editing. You can switch between views at any time.",
      keywords: "calendar view, list view, what does it show, how to switch, comms planner view",
      displayOrder: 70,
    },
    {
      category: "Comms Planner",
      question: "What does the 'Methodology' button do in the Comms Planner?",
      answer: "The Methodology button opens a panel explaining how the Comms Planner scores each type of activity — which content types score highest, why, and what factors the platform considers. It's designed to help you understand the scoring rationale so you can plan strategically.",
      keywords: "methodology button, how scoring works, comms planner, scoring rationale, what does it do",
      displayOrder: 80,
    },
    {
      category: "Comms Planner",
      question: "What do the Status colours mean in the Comms Planner?",
      answer: "Status colours track each planned activity through its lifecycle: Draft (grey) means the activity has been added but content hasn't been started; In Progress (amber) means content is being created; Review (blue) means it's ready for sign-off; Final (green) means approved and ready to publish. These map to the content statuses in the Archive.",
      keywords: "status colours, draft, in progress, review, final, comms planner, status, what do they mean",
      displayOrder: 90,
    },
    {
      category: "Comms Planner",
      question: "What happens when I click a row in the Comms Planner?",
      answer: "Clicking a row opens the detail panel for that activity, where you can view any attached content, edit the planned date, update the status, or navigate directly to the Content Creator or Optimiser to work on the associated piece. If content has already been created for that activity, there will be a link to open it.",
      keywords: "click row, planner row, activity detail, edit, open content, comms planner",
      displayOrder: 100,
    },
    // ── Earned Media Tracker ──────────────────────────────────────────────────
    {
      category: "Earned Media Tracker",
      question: "What is the Earned Media Tracker and where do I find it?",
      answer: "The Earned Media Tracker is a log of all earned media coverage — articles, mentions, podcasts, broadcasts — your brand has received. It lives within the Report / Measure section of the platform. You can populate it via AI Coverage Search (which finds recent coverage automatically) or by adding entries manually.",
      keywords: "earned media tracker, what is it, where to find, coverage log, report section",
      displayOrder: 10,
    },
    {
      category: "Earned Media Tracker",
      question: "What is 'AI Coverage Search'?",
      answer: "AI Coverage Search automatically searches for recent online coverage of your brand across news sources and digital media. Enter a date range and optionally a spokesperson name or region, then click Run AI Search. Results are returned as a list of coverage items that you can review and add to your tracker.",
      keywords: "ai coverage search, automated search, find coverage, online mentions, run ai search, how does it work",
      displayOrder: 20,
    },
    {
      category: "Earned Media Tracker",
      question: "How does the Manual Log work in the Earned Media Tracker?",
      answer: "The Manual Log lets you add a coverage item by hand — useful for broadcast coverage, print publications, or anything the AI search doesn't find automatically. Fill in the title, publication/outlet, coverage type, URL (if available), and estimated reach, then click Add to Tracker. The item is saved permanently to your project.",
      keywords: "manual log, add manually, coverage, how to add, manual entry, tracker, print, broadcast",
      displayOrder: 30,
    },
    {
      category: "Earned Media Tracker",
      question: "What is 'Reach' in the Earned Media Tracker?",
      answer: "Reach is the estimated total audience for a piece of coverage — the number of people who could have seen or heard the mention. For online articles it may be based on publication traffic estimates; for broadcast, it uses typical audience figures. Reach is summed across all entries to give you a Total Reach metric for the reporting period.",
      keywords: "reach, what is it, audience, total reach, coverage metric, how measured",
      displayOrder: 40,
    },
    {
      category: "Earned Media Tracker",
      question: "What does 'Export' do from the Earned Media Tracker?",
      answer: "Export downloads your tracker entries as a CSV file. It includes all coverage items in the selected date range — title, outlet, type, URL, reach, date, and spokesperson. The CSV is formatted for import into spreadsheets or client reporting tools.",
      keywords: "export, csv, download, tracker export, coverage report, what does it do",
      displayOrder: 50,
    },
    {
      category: "Earned Media Tracker",
      question: "What is the 'Authority Trend Chart' in the Report section?",
      answer: "The Authority Trend Chart shows your Authority Index score over time — plotted from each saved LLM Check audit run. It lets you see whether your AI visibility is improving, declining, or plateauing, and correlate changes with specific communications activities. You need at least two saved audits for trend data to appear.",
      keywords: "authority trend chart, trend, over time, report, authority index, chart, progress",
      displayOrder: 60,
    },
    {
      category: "Earned Media Tracker",
      question: "How do I delete entries from the Earned Media Tracker?",
      answer: "To remove a single entry, hover over the row and click the delete icon. To remove multiple entries at once, tick the checkboxes on the left of each row, then click the 'Delete selected' button that appears at the top of the table. Deletions are permanent — there is no undo.",
      keywords: "delete, remove entry, bulk delete, tracker, delete selected, how to delete",
      displayOrder: 70,
    },
    // ── Marketing Intelligence ────────────────────────────────────────────────
    {
      category: "Marketing Intelligence",
      question: "What is the Marketing Intelligence page?",
      answer: "Marketing Intelligence helps you identify speaking opportunities, industry awards, and events that are relevant to your brand's sector and messaging. It searches a database of upcoming opportunities and scores each one for its predicted GEO impact — so you can prioritise the opportunities most likely to boost your AI visibility.",
      keywords: "marketing intelligence, what is it, awards, events, speaking, opportunities, how does it work",
      displayOrder: 10,
    },
    {
      category: "Marketing Intelligence",
      question: "What are the 'Actionable Opportunities' at the top of Marketing Intelligence?",
      answer: "Actionable Opportunities are the top 3 highest-scoring events or awards for your brand at this moment — hand-picked by the platform based on your Intake Form context, current GEO positioning, and submission deadlines. These are the ones to act on first for the fastest visibility uplift.",
      keywords: "actionable opportunities, top 3, marketing intelligence, best opportunities, priorities",
      displayOrder: 20,
    },
    {
      category: "Marketing Intelligence",
      question: "What does '[C] Confirmed' and '[U] Unconfirmed' mean on events?",
      answer: "[C] Confirmed means the event details — date, location, submission deadline — have been verified against the official event website. [U] Unconfirmed means the entry is based on prior-year data and the current year's details haven't yet been announced. Always check official sources for Unconfirmed entries before committing.",
      keywords: "confirmed, unconfirmed, c u tag, event status, verified, marketing intelligence, check details",
      displayOrder: 30,
    },
    {
      category: "Marketing Intelligence",
      question: "What does 'LLM Brief' generate?",
      answer: "LLM Brief generates a customised written brief for a selected opportunity — a tailored overview of what the award or event is looking for, what makes a strong submission, and how your brand's key messages align with the judging criteria. It's designed to brief your team or copywriter quickly and accurately.",
      keywords: "llm brief, generate brief, award brief, event brief, what does it do, marketing intelligence",
      displayOrder: 40,
    },
    {
      category: "Marketing Intelligence",
      question: "What does 'Push to Project Set-Up' do from Marketing Intelligence?",
      answer: "Push to Project Set-Up adds selected events or awards directly to the relevant section of your Intake Form — so they become part of your formal GEO strategy and can influence audit queries and content generation. Use this to formally commit to pursuing an opportunity.",
      keywords: "push to project setup, marketing intelligence, add to intake form, events, awards, what does it do",
      displayOrder: 50,
    },
    {
      category: "Marketing Intelligence",
      question: "What is the 'Authority Score' shown on each event?",
      answer: "The Authority Score (0-100) on an event or award estimates how much GEO impact securing that opportunity would have for your brand — based on the event's reach, prestige, and relevance to your sector and key messages. Higher scores indicate opportunities with greater potential to move your Authority Index.",
      keywords: "authority score, event score, 0-100, marketing intelligence, what is it, impact score",
      displayOrder: 60,
    },
    // ── Website Content GEO ───────────────────────────────────────────────────
    {
      category: "Website Content GEO",
      question: "What is the Website Content GEO audit?",
      answer: "Website Content GEO analyses the actual text content of your website pages and scores how well each page is aligned with your brand's key messages, topics, and GEO signals from the Intake Form. It's different from the Technical GEO audit — that checks structure; this checks content quality and message alignment.",
      keywords: "website content geo, what is it, content audit, message alignment, geo score, pages",
      displayOrder: 10,
    },
    {
      category: "Website Content GEO",
      question: "What does 'Scan Site Content' do?",
      answer: "Scan Site Content crawls your website's publicly accessible pages and retrieves the content for analysis. It then compares each page's content against your Intake Form data — measuring how well your live website content reflects your brand's key messages and GEO topics. Results show per-page alignment scores and recommended improvements.",
      keywords: "scan site content, what does it do, crawl, analyse pages, website, content scan",
      displayOrder: 20,
    },
    {
      category: "Website Content GEO",
      question: "What is an 'Alignment Score' on the Website Content GEO?",
      answer: "An Alignment Score measures how closely the content on a specific web page matches the key messages, semantic topics, and brand claims defined in your Intake Form. A high alignment score (80+) means the page is strongly on-message. A low score (below 50) means the page either misses key messages or uses language inconsistent with your GEO strategy.",
      keywords: "alignment score, what is it, website content geo, on message, page score, match",
      displayOrder: 30,
    },
    {
      category: "Website Content GEO",
      question: "What does 'Push to Project Set-Up' do from Website Content GEO?",
      answer: "Push to Project Set-Up takes the recommended improvements from the Website Content GEO audit and adds them as action items in your Intake Form — so your next round of content creation and optimisation targets the specific gaps the audit identified. It keeps your Intake Form in sync with your actual website content.",
      keywords: "push to project setup, website content geo, intake form, recommendations, what does it do",
      displayOrder: 40,
    },
    // ── Media Research ────────────────────────────────────────────────────────
    {
      category: "Media Research & Media Database",
      question: "What is the Media Research tool?",
      answer: "Media Research recommends relevant journalists, publications, and media outlets based on the brand's sector, topics, and target audience. It helps communications teams build and maintain the media relationships that underpin earned media visibility.",
      keywords: "media research, what is it, journalists, publications, media database, contacts",
      displayOrder: 10,
    },
    {
      category: "Media Research & Media Database",
      question: "Is the Media Database live or static?",
      answer: "The Media Database is regularly updated but reflects a point-in-time snapshot of journalist coverage and beats. Always verify contact details and beat relevance before outreach — journalists move between publications frequently. Use the tool to identify who to prioritise, then confirm details via the publication's website.",
      keywords: "media database, live, static, up to date, accurate, verify, contacts",
      displayOrder: 20,
    },
    {
      category: "Media Research & Media Database",
      question: "How do I add a journalist or outlet to my media list?",
      answer: "From any Media Research result, click 'Save to Media List.' Saved contacts appear in your Media Database. You can tag contacts, add notes, and filter by beat, publication, or tier.",
      keywords: "save journalist, media list, add contact, how to save, media database",
      displayOrder: 30,
    },
    {
      category: "Media Research & Media Database",
      question: "What do [V], [P], and [U] tags mean on journalist results?",
      answer: "[V] Verified means the journalist's beat and contact details have been confirmed against a live source. [P] Inferred (Probable) means the beat is estimated from recent coverage patterns but not directly confirmed. [U] Unverified means the journalist has been identified as potentially relevant but details should be checked before outreach. Always prioritise [V] contacts for time-sensitive campaigns.",
      keywords: "v verified p inferred u unverified, journalist tags, what do they mean, media research, confidence, status",
      displayOrder: 40,
    },
    {
      category: "Media Research & Media Database",
      question: "What is a 'Pitch Angle' in the Media Research results?",
      answer: "A Pitch Angle is a suggested approach for pitching a specific journalist or outlet — based on their recent coverage patterns, beat focus, and what's likely to resonate with their audience. The platform generates these automatically to save you the research time. Treat them as a starting point; personalise each pitch before sending.",
      keywords: "pitch angle, what is it, media research, pitch suggestion, how to pitch, journalist",
      displayOrder: 50,
    },
    {
      category: "Media Research & Media Database",
      question: "What does 'Recommend Media' do?",
      answer: "Recommend Media takes a selected piece of content from your Archive (a press release, article, or other piece) and returns a ranked list of journalists and outlets most likely to cover it — based on the content's topics, tone, and format. It's the most efficient way to build a targeted media list for a specific press release.",
      keywords: "recommend media, what does it do, media list, content based, targeted, journalists, media research",
      displayOrder: 60,
    },
    {
      category: "Media Research & Media Database",
      question: "What is the difference between the 'Outlets' and 'Contacts' tabs in the Media Database?",
      answer: "Outlets are publications, websites, or broadcasters — the media organisations. Contacts are individual journalists or contributors at those organisations. You can add outlets first and then link contacts to them. The Outlets tab lets you filter and browse by publication type, reach, and sector; the Contacts tab lets you filter by beat, outlet, or tier.",
      keywords: "outlets tab, contacts tab, difference, media database, publications, journalists, how organised",
      displayOrder: 70,
    },
    {
      category: "Media Research & Media Database",
      question: "What is 'Global vs Project-specific' scoping in the Media Database?",
      answer: "Global contacts and outlets are shared across all projects in your agency account — useful for journalists you pitch regularly regardless of which client's story you're working on. Project-specific entries are visible only within the project they were added to — useful for niche contacts relevant only to one client. You set the scope when adding a new entry.",
      keywords: "global, project specific, scoping, media database, shared, visible, which project, scope",
      displayOrder: 80,
    },
    // ── Report & Dashboard ────────────────────────────────────────────────────
    {
      category: "Archive & Reports",
      question: "What is saved in the Archive?",
      answer: "The Archive stores all content you've created or optimised in the platform — press releases, articles, social posts, and more. It also stores completed audits and planner exports. Content is organised by project and date, and is searchable.",
      keywords: "archive, what is saved, content library, history, previous work, stored",
      displayOrder: 10,
    },
    {
      category: "Archive & Reports",
      question: "Where can I find my previous audit results?",
      answer: "Previous audit results are accessible in two places: (1) in the sidebar under the relevant audit section (LLM Check or Technical GEO), where the 3 most recent runs are shown; and (2) in the Archive section, where all saved audits are listed with their scores and dates.",
      keywords: "previous audits, find old results, audit history, past results, saved audits",
      displayOrder: 20,
    },
    {
      category: "Archive & Reports",
      question: "Can I compare results across multiple audits?",
      answer: "Yes. The Report / Measure section provides trend charts and comparisons across saved audits, so you can track your Authority Index, citation rate, and content GEO scores over time. You need at least two saved audits to see trend data.",
      keywords: "compare audits, trend, over time, measure, report, multiple audits, track progress",
      displayOrder: 30,
    },
    {
      category: "Archive & Reports",
      question: "How do I export a report to share with a client?",
      answer: "From the Report / Measure page, click 'Export Report.' This generates a PDF or HTML report containing your key metrics, trend charts, and recommendations. Reports are branded with the AIO Fusion logo and can be customised with your agency branding on request.",
      keywords: "export report, pdf, share, client report, download, white label, branded report",
      displayOrder: 40,
    },
    {
      category: "Archive & Reports",
      question: "How long is data retained in the Archive?",
      answer: "All saved content, audits, and reports are retained for the lifetime of your account. There is no automatic expiry. If you close or pause your account, we retain your data for 90 days before permanent deletion — giving you time to export anything important.",
      keywords: "data retention, how long, archive, storage, delete, expiry, account closed",
      displayOrder: 50,
    },
    {
      category: "Archive & Reports",
      question: "What does the main Dashboard show?",
      answer: "The Dashboard gives you an at-a-glance overview of your project's current state: your latest Authority Index score (from the most recent LLM Check), your Intake Form completion percentage, quick-link stat cards showing how many content pieces are in Draft, In Progress, Review, and Final status, and lock-status indicators for each audit tool.",
      keywords: "dashboard, what does it show, overview, authority index, stat cards, quick view, main page",
      displayOrder: 60,
    },
    {
      category: "Archive & Reports",
      question: "What do the lock icons on the Dashboard mean?",
      answer: "Lock icons on the Dashboard appear next to audit tools (LLM Check, Technical GEO) when they're in their waiting period — showing how many days remain before you can run them again. A green unlocked icon means the tool is ready to run. Clicking the icon takes you directly to that audit tool.",
      keywords: "lock icons, dashboard, locked, audit waiting period, days remaining, when can I run, lock",
      displayOrder: 70,
    },
    {
      category: "Archive & Reports",
      question: "What are the stat cards (Total Articles, In Planner, In Draft, Final/Ready) on the Dashboard?",
      answer: "These cards count your content pieces by status across the project. 'Total Articles' is all content created. 'In Planner' is how many are scheduled in the Comms Planner. 'In Draft' is work in progress. 'Final / Ready' is content approved and ready to release. Clicking any card takes you to the filtered Archive view.",
      keywords: "stat cards, total articles, in planner, in draft, final ready, dashboard, content count, what are they",
      displayOrder: 80,
    },
    // ── Release Gateway ────────────────────────────────────────────────────────
    {
      category: "Release Gateway",
      question: "What is the Release Gateway?",
      answer: "The Release Gateway is where you distribute finalised content to wire services, social media, and other distribution channels. Any content piece marked 'Final' in the Archive appears here. From the Release Gateway you can download the piece, share it to LinkedIn, or submit it to connected press wire services.",
      keywords: "release gateway, what is it, distribution, wire services, publish, final content, how to release",
      displayOrder: 10,
    },
    {
      category: "Release Gateway",
      question: "What wire services are supported in the Release Gateway?",
      answer: "The Release Gateway supports integration with major press wire services including PR Newswire, Business Wire, and EIN Presswire. Connection status for each service is shown in the Gateway. If a service shows as 'Not connected', contact your platform admin or support to set up the integration.",
      keywords: "wire services, pr newswire, business wire, ein presswire, release gateway, which services, distribution",
      displayOrder: 20,
    },
    {
      category: "Release Gateway",
      question: "What does 'LinkedIn Share' do in the Release Gateway?",
      answer: "LinkedIn Share opens a pre-formatted LinkedIn post based on the selected content piece — with a suggested caption and a link to the content. You'll be taken to LinkedIn in a new tab where you can review and post. The content text itself is formatted to fit LinkedIn's character limits.",
      keywords: "linkedin share, social media, release gateway, post to linkedin, what does it do, social",
      displayOrder: 30,
    },
    {
      category: "Release Gateway",
      question: "What content appears in the Release Gateway?",
      answer: "Only content pieces with a status of 'Final' appear in the Release Gateway. Content in Draft, In Progress, or Review status is not shown. To move a piece to Final, update its status in the Content Creator or Archive. Once Final, it appears in the Gateway automatically.",
      keywords: "what appears, release gateway, final status, content, archive, which pieces show",
      displayOrder: 40,
    },
    // ── Account & Access Management ───────────────────────────────────────────
    {
      category: "Account & Access Management",
      question: "How do I add a new team member to my agency?",
      answer: "Admin and agency accounts can add team members from the User Management page. Go to the platform home, click your profile, then 'Manage Users.' Click 'Add User,' enter their email and set their role. They'll receive an invitation email with a temporary password.",
      keywords: "add user, new team member, invite, user management, add account, sub-account",
      displayOrder: 10,
    },
    {
      category: "Account & Access Management",
      question: "How do I reset a user's password?",
      answer: "Admin accounts can reset any user's password from the User Management page. Click the three-dot menu next to the user, select 'Change Password,' and set a new temporary password. The user will be prompted to change it on next login.",
      keywords: "reset password, change password, forgot password, admin, user management",
      displayOrder: 20,
    },
    {
      category: "Account & Access Management",
      question: "Can I give a client read-only access to their results?",
      answer: "Yes. Client accounts have access to their own project's audit results, reports, and content — but cannot manage users or access other projects. To set up a client with view-only access, create a Client role account and assign it to the relevant project.",
      keywords: "client access, read only, view only, share results, client login, restrict access",
      displayOrder: 30,
    },
    {
      category: "Account & Access Management",
      question: "How do I delete a user or project?",
      answer: "User accounts can be archived (not permanently deleted) from the User Management page by an Admin. Archived users lose access but their data is retained. Projects can be deleted from the Project Hub — this is permanent and cannot be undone.",
      keywords: "delete user, archive user, remove user, delete project, deactivate",
      displayOrder: 40,
    },
    {
      category: "Account & Access Management",
      question: "What is the 'Impersonation' feature?",
      answer: "'View Account' (impersonation) allows an admin to log in as another account to diagnose issues or verify what a user sees. It's available from the User Management page. All actions taken while impersonating are logged against the original admin account for audit trail purposes.",
      keywords: "impersonation, view account, log in as, admin feature, audit trail, user view",
      displayOrder: 50,
    },
    {
      category: "Account & Access Management",
      question: "How do I change the account email address?",
      answer: "Contact your agency admin or platform support to change the email address on an account. For security reasons, email changes require verification. If you're the admin, email info@aiofusions.ai with the account username and the new email address.",
      keywords: "change email, update email, email address, account email, username",
      displayOrder: 60,
    },
    // ── Billing & Payments ─────────────────────────────────────────────────────
    {
      category: "Billing & Payments",
      question: "How is AIO Fusion priced?",
      answer: "AIO Fusion is available on a monthly subscription basis, with pricing based on the number of projects and user accounts. Agency plans cover multiple client projects; in-house plans are single-brand. For current pricing, visit aiofusions.ai/pricing or contact info@aiofusions.ai.",
      keywords: "pricing, cost, how much, subscription, plans, billing, monthly fee",
      displayOrder: 10,
    },
    {
      category: "Billing & Payments",
      question: "What counts as an 'action' for fair usage?",
      answer: "An 'action' is any content generation or optimisation run — creating a press release, optimising an article, running the Content Creator, etc. Audit runs (LLM Check, Technical GEO) and LLM query generation have their own separate 21-day limits and don't count towards the 50-action monthly fair usage total.",
      keywords: "action, fair usage, what counts, 50 actions, usage, monthly limit, content actions",
      displayOrder: 20,
    },
    {
      category: "Billing & Payments",
      question: "How do I upgrade or change my plan?",
      answer: "Contact info@aiofusions.ai to discuss plan changes. We'll review your usage and recommend the right plan. Changes are applied at the start of the next billing period.",
      keywords: "upgrade, change plan, billing, subscription change, more projects, higher limit",
      displayOrder: 30,
    },
    // ── Bug / Technical Issue ──────────────────────────────────────────────────
    {
      category: "Bug / Technical Issue",
      question: "The page is loading slowly or not loading at all — what should I do?",
      answer: "First, try a hard refresh (Ctrl+Shift+R on Windows, Cmd+Shift+R on Mac). If the issue persists, check your internet connection. If you're still having trouble, try clearing your browser cache. If none of these work, contact support and include your browser type and version.",
      keywords: "slow, not loading, blank page, refresh, cache, browser issue, loading",
      displayOrder: 10,
    },
    {
      category: "Bug / Technical Issue",
      question: "I'm getting an error when I try to run an audit — what's wrong?",
      answer: "Audit errors are usually caused by one of three things: (1) an incomplete Intake Form — ensure the company name, sector, and website URL are filled in; (2) a temporary AI API outage — try again in a few minutes; (3) a session timeout — try logging out and back in. If the problem persists, contact support with a screenshot of the error.",
      keywords: "audit error, error running audit, something went wrong, api error, try again, fix",
      displayOrder: 20,
    },
    {
      category: "Bug / Technical Issue",
      question: "The content generator produced garbled or cut-off output — is this a bug?",
      answer: "Occasionally AI model responses can be incomplete or garbled, especially for very long documents. Try re-running the generation — results will differ slightly each time. If cut-off output happens consistently, reduce the length of the input and try again. If the problem persists, contact support.",
      keywords: "garbled output, cut off, incomplete content, generation error, ai response, weird output",
      displayOrder: 30,
    },
    {
      category: "Bug / Technical Issue",
      question: "I can't log in — I'm sure my password is correct. What do I do?",
      answer: "First, check Caps Lock is off. Try resetting your password using the 'Forgot password' link. If you don't receive a reset email within 5 minutes, check your spam folder. If you still can't log in, contact your agency admin or email info@aiofusions.ai with your username.",
      keywords: "can't login, wrong password, locked out, forgot password, access, reset",
      displayOrder: 40,
    },
    {
      category: "Bug / Technical Issue",
      question: "My saved work has disappeared — can it be recovered?",
      answer: "Saved audits, content, and planner data are stored server-side and are not lost on browser refresh. If data appears missing, try logging out and back in to force a full re-sync. If data is genuinely missing, contact support immediately — we maintain database backups and can usually recover recent work.",
      keywords: "data lost, disappeared, missing data, recovery, restore, saved work gone",
      displayOrder: 50,
    },
  ];

  await db.insert(supportFaqTable).values(entries);
  logger.info({ count: entries.length }, "seedSupportFaq: FAQ library seeded successfully");
}
