export const TRADE_MEDIA_CATEGORIES: string[] = [
  "Accounting/Audit",
  "AdTech & MarTech",
  "Agricultural Supplies",
  "Agricultural Technology (AgTech)",
  "Architecture",
  "Artificial Intelligence (AI)",
  "Automotive Technology",
  "Aviation",
  "Biotechnology",
  "Branding & Brand Design",
  "Building Services",
  "Business Consulting & Strategy",
  "Car Manufacturing",
  "Care Homes/Social Care",
  "Central & Local Government",
  "CGI & Visual Effects",
  "Chemicals Manufacturing",
  "Cloud Computing",
  "Commercial Property",
  "Commercial Vehicles",
  "Construction Technology (ConTech)",
  "Corporate & Trade Finance",
  "Courier Services",
  "Customer Experience (CX)",
  "Cybersecurity",
  "Data Management",
  "Dealerships/Retail",
  "Defence & Security",
  "Drug Development",
  "E-commerce/Online Retail",
  "EdTech (Education Technology)",
  "E-learning",
  "Electric Vehicles (EVs)",
  "Electricity Generation & Distribution",
  "Emergency Services",
  "Energy Efficiency",
  "Energy Trading",
  "Engineering (Civil, Structural, MEP)",
  "Engineering Services",
  "Environmental Management & Consulting",
  "Environmental Technology",
  "Events & Venues",
  "Facilities Management",
  "Farm Equipment & Machinery",
  "Farming",
  "Fashion Retail",
  "Film & Television Production",
  "FinTech & Banking",
  "Fleet Management",
  "Food & Beverage Manufacturing",
  "Food Service/Contract Catering",
  "Gaming & Casinos",
  "Gaming & Esports",
  "General business",
  "General business technology",
  "Green energy",
  "Grocery Retail",
  "Health Technology (HealthTech)",
  "Higher Education",
  "Hotels & Accommodation",
  "HR & Recruitment",
  "Industrial Property",
  "Ingredients & Suppliers",
  "Insurance Technology (InsurTech)",
  "Investment & Wealth Management",
  "IT Infrastructure",
  "Laboratory Services",
  "Last-Mile Delivery",
  "Legal Services",
  "Logistics Technology",
  "Manufacturing Technology",
  "Maritime/Shipping",
  "Market Research",
  "Marketing & Advertising",
  "Media & Entertainment",
  "Medical Devices",
  "Medical Research",
  "Mental Health Services",
  "Music Industry",
  "National news brands",
  "Oil & Gas",
  "Packaging & Product Design",
  "Payments/Payment Processing",
  "Pharmaceuticals",
  "Ports & Terminals",
  "Private Healthcare",
  "Procurement & Supply Chain",
  "Property & Facilities Technology",
  "Property Development",
  "Property Investment",
  "Public Healthcare",
  "Public Relations (PR)",
  "Public Services",
  "Pubs & Bars",
  "Rail",
  "RegTech (Regulatory Technology)",
  "Renewable Energy",
  "Residential Property",
  "Restaurants & Catering",
  "Retail Technology",
  "Road Transport/Haulage",
  "Robotics",
  "SaaS & Enterprise Software",
  "Schools (Primary & Secondary)",
  "Service Design",
  "Specialty Retail",
  "Sports & Recreation Facilities",
  "Telecommunications",
  "Third Sector Organisations",
  "Training Providers",
  "Travel & Tourism",
  "UX & UI",
  "Veterinary Services",
  "Warehousing & Distribution",
  "Waste Management & Recycling",
  "Water & Wastewater",
];
