// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/account-settings/Current.tsx": () => import("../components/mockups/account-settings/Current.tsx"),
  "./components/mockups/account-settings/EmbeddedOnboarding.tsx": () => import("../components/mockups/account-settings/EmbeddedOnboarding.tsx"),
  "./components/mockups/account-settings/FocusedOnboarding.tsx": () => import("../components/mockups/account-settings/FocusedOnboarding.tsx"),
  "./components/mockups/account-settings/UnifiedSiteSystem.tsx": () => import("../components/mockups/account-settings/UnifiedSiteSystem.tsx"),
  "./components/mockups/account-settings/UpdatedDashboard.tsx": () => import("../components/mockups/account-settings/UpdatedDashboard.tsx"),
  "./components/mockups/account-settings/UpdatedProjectSetup.tsx": () => import("../components/mockups/account-settings/UpdatedProjectSetup.tsx"),
  "./components/mockups/account-settings/WiderReadable.tsx": () => import("../components/mockups/account-settings/WiderReadable.tsx"),
  "./components/mockups/aio-fusion-demo/FullDemo.tsx": () => import("../components/mockups/aio-fusion-demo/FullDemo.tsx"),
  "./components/mockups/aio-fusion-light/AuthorityPlanner.tsx": () => import("../components/mockups/aio-fusion-light/AuthorityPlanner.tsx"),
  "./components/mockups/aio-fusion-light/ContentOptimiser.tsx": () => import("../components/mockups/aio-fusion-light/ContentOptimiser.tsx"),
  "./components/mockups/aio-fusion-light/Dashboard.tsx": () => import("../components/mockups/aio-fusion-light/Dashboard.tsx"),
  "./components/mockups/aio-fusion-light/GeoDiagnostic.tsx": () => import("../components/mockups/aio-fusion-light/GeoDiagnostic.tsx"),
  "./components/mockups/aio-fusion/AuthorityPlanner.tsx": () => import("../components/mockups/aio-fusion/AuthorityPlanner.tsx"),
  "./components/mockups/aio-fusion/ContentOptimiser.tsx": () => import("../components/mockups/aio-fusion/ContentOptimiser.tsx"),
  "./components/mockups/aio-fusion/Dashboard.tsx": () => import("../components/mockups/aio-fusion/Dashboard.tsx"),
  "./components/mockups/aio-fusion/GeoDiagnostic.tsx": () => import("../components/mockups/aio-fusion/GeoDiagnostic.tsx"),
  "./components/mockups/brand-review/Home.tsx": () => import("../components/mockups/brand-review/Home.tsx"),
  "./components/mockups/brand-review/Onboarding.tsx": () => import("../components/mockups/brand-review/Onboarding.tsx"),
  "./components/mockups/brand-review/Report.tsx": () => import("../components/mockups/brand-review/Report.tsx"),
  "./components/mockups/brand-review/Settings.tsx": () => import("../components/mockups/brand-review/Settings.tsx"),
  "./components/mockups/brand-review/Setup.tsx": () => import("../components/mockups/brand-review/Setup.tsx"),
  "./components/mockups/feature-cards/Current.tsx": () => import("../components/mockups/feature-cards/Current.tsx"),
  "./components/mockups/feature-cards/Editorial.tsx": () => import("../components/mockups/feature-cards/Editorial.tsx"),
  "./components/mockups/feature-cards/Immersive.tsx": () => import("../components/mockups/feature-cards/Immersive.tsx"),
  "./components/mockups/feature-cards/Refined.tsx": () => import("../components/mockups/feature-cards/Refined.tsx")
};
