// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aio-fusion-demo/FullDemo.tsx": () => import("../components/mockups/aio-fusion-demo/FullDemo.tsx"),
  "./components/mockups/aio-fusion-light/AuthorityPlanner.tsx": () => import("../components/mockups/aio-fusion-light/AuthorityPlanner.tsx"),
  "./components/mockups/aio-fusion-light/ContentOptimiser.tsx": () => import("../components/mockups/aio-fusion-light/ContentOptimiser.tsx"),
  "./components/mockups/aio-fusion-light/Dashboard.tsx": () => import("../components/mockups/aio-fusion-light/Dashboard.tsx"),
  "./components/mockups/aio-fusion-light/GeoDiagnostic.tsx": () => import("../components/mockups/aio-fusion-light/GeoDiagnostic.tsx"),
  "./components/mockups/aio-fusion/AuthorityPlanner.tsx": () => import("../components/mockups/aio-fusion/AuthorityPlanner.tsx"),
  "./components/mockups/aio-fusion/ContentOptimiser.tsx": () => import("../components/mockups/aio-fusion/ContentOptimiser.tsx"),
  "./components/mockups/aio-fusion/Dashboard.tsx": () => import("../components/mockups/aio-fusion/Dashboard.tsx"),
  "./components/mockups/aio-fusion/GeoDiagnostic.tsx": () => import("../components/mockups/aio-fusion/GeoDiagnostic.tsx")
};
